spring.application.name=SocialMediaAnalyzer
spring.config.import=optional:file:./application-local.properties

meta.graph.api.base-url=https://graph.facebook.com/v25.0
meta.graph.api.access-token=${META_ACCESS_TOKEN:}
meta.graph.api.page-id=1074658132407512
meta.graph.api.post-limit=20
meta.graph.api.use-demo-on-empty=true
server.port=8090